# start the server:
#     docker-compose up --build
#
# use mysql cli:
#     docker-compose exec mysql mysql -uroot -p
# (the /docker/trav directory is mounted for easier sourcing and export)
#
# save the DB:
#     docker-compose exec mysql /usr/bin/mysqldump -u root --password=able chrall > 20180807-chrall.sql
version: "3"
services:
        gogo:
                build:
                        context: .
                        dockerfile: ./docker/go/Dockerfile
                restart: always
                ports:
                        - "9090:9090"
                links:
                        - mysql
        mysql:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: able
                volumes:
                        - chrall-mysql:/var/lib/mysql
                        - ./docker/trav:/trav
volumes:
        chrall-mysql:

