include $(GOROOT)/src/Make.inc

TARG=gogo
GOFILES=\
	main/handler.go\
	main/roothandler.go\
	main/wellhandler.go\
	main/jsonhandler.go\
	main/chrallhandler.go\
	main/gogo.go\

include $(GOROOT)/src/Make.cmd
