include $(GOROOT)/src/Make.inc

TARG=gogo
GOFILES=\
	main/cdm.go\
	main/bestiaryextract.go\
	main/cdmstore.go\
	main/handler.go\
	main/roothandler.go\
	main/bucketdecoder.go\
	main/wellhandler.go\
	main/bestiaryhandler.go\
	main/jsonposthandler.go\
	main/jsongethandler.go\
	main/chrallhandler.go\
	main/gogo.go\

include $(GOROOT)/src/Make.cmd
